name: micro
summary: A modern and intuitive terminal-based text editor
description: |
  Micro is a terminal-based text editor that aims to be easy to use and
  intuitive, while also taking advantage of the full capabilities of modern
  terminals.
confinement: classic
adopt-info: micro
base: core24

apps:
  micro:
    command: bin/micro

parts:
  micro:
    source: .
    source-type: git
    plugin: go
    build-snaps: [go]
    build-packages: [make]
    build-attributes: [no-patchelf]
    override-pull: |
      craftctl default
      version="$(go run $CRAFT_PART_SRC/tools/build-version.go)"
      [ -n "$(echo $version | grep "dev")" ] && grade=devel || grade=stable
      craftctl set version="$version"
      craftctl set grade="$grade"
    override-build: |
      make build-tags
      mkdir $CRAFT_PART_INSTALL/bin
      mv ./micro $CRAFT_PART_INSTALL/bin/
