name: micro
version: master
summary: A modern and intuitive terminal-based text editor
description: |
  Micro is a terminal-based text editor that aims to be easy to use and
  intuitive, while also taking advantage of the full capabilities of modern
  terminals.
confinement: strict

apps:
  micro:
    command: bin/micro
    plugs: [home]

parts:
  micro:
    source: .
    plugin: go
    go-importpath: github.com/zyedidia/micro
    go-packages: [github.com/zyedidia/micro/cmd/micro]
    build-packages: [git]
