name: micro
version: master
summary: A modern and intuitive terminal-based text editor
description: |
  Micro is a terminal-based text editor that aims to be easy to use and
  intuitive, while also taking advantage of the full capabilities of modern
  terminals.
confinement: classic

apps:
  micro:
    command: bin/micro

parts:
  micro:
    source: .
    plugin: go
    go-importpath: github.com/zyedidia/micro/cmd/micro
