filetype: pc

detect:
    filename: "\\.pc$"

rules:
    - preproc: "^(Name|Description|URL|Version|Conflicts|Cflags):"
    - preproc: "^(Requires|Libs)(\\.private)?:"
    - symbol.operator: "="
    - identifier.var: "\\$\\{[A-Za-z_]\\w*\\}"
    - indent-char.whitespace: "[[:space:]]+$"
    - indent-char: "	+ +| +	+"
