//go:build !darwin
// +build !darwin

package action

var bufdefaults = map[string]string{
	"Up":               "CursorUp",
	"Down":             "CursorDown",
	"Right":            "CursorRight",
	"Left":             "CursorLeft",
	"Shift-Up":         "SelectUp",
	"Shift-Down":       "SelectDown",
	"Shift-Left":       "SelectLeft",
	"Shift-Right":      "SelectRight",
	"Ctrl-Left":        "WordLeft",
	"Ctrl-Right":       "WordRight",
	"Alt-Up":           "MoveLinesUp",
	"Alt-Down":         "MoveLinesDown",
	"Shift-Ctrl-Right": "SelectWordRight",
	"Shift-Ctrl-Left":  "SelectWordLeft",
	"Alt-Left":         "StartOfTextToggle",
	"Alt-Right":        "EndOfLine",
	"Shift-Alt-Left":   "SelectToStartOfTextToggle",
	"Shift-Home":       "SelectToStartOfTextToggle",
	"Shift-Alt-Right":  "SelectToEndOfLine",
	"Shift-End":        "SelectToEndOfLine",
	"Ctrl-Up":          "CursorStart",
	"Ctrl-Down":        "CursorEnd",
	"Shift-Ctrl-Up":    "SelectToStart",
	"Shift-Ctrl-Down":  "SelectToEnd",
	"Alt-{":            "ParagraphPrevious",
	"Alt-}":            "ParagraphNext",
	"Enter":            "InsertNewline",
	"Ctrl-H":           "Backspace",
	"Backspace":        "Backspace",
	"OldBackspace":     "Backspace",
	"Alt-Ctrl-h":       "DeleteWordLeft",
	"Alt-Backspace":    "DeleteWordLeft",
	"Tab":              "Autocomplete|IndentSelection|InsertTab",
	"Backtab":          "CycleAutocompleteBack|OutdentSelection|OutdentLine",
	"Ctrl-o":           "OpenFile",
	"Ctrl-s":           "Save",
	"Ctrl-f":           "Find",
	"Alt-F":            "FindLiteral",
	"Ctrl-n":           "FindNext",
	"Ctrl-p":           "FindPrevious",
	"Alt-[":            "DiffPrevious|CursorStart",
	"Alt-]":            "DiffNext|CursorEnd",
	"Ctrl-z":           "Undo",
	"Ctrl-y":           "Redo",
	"Ctrl-c":           "Copy|CopyLine",
	"Ctrl-x":           "Cut|CutLine",
	"Ctrl-k":           "CutLine",
	"Ctrl-d":           "Duplicate|DuplicateLine",
	"Ctrl-v":           "Paste",
	"Ctrl-a":           "SelectAll",
	"Ctrl-t":           "AddTab",
	"Alt-,":            "PreviousTab|LastTab",
	"Alt-.":            "NextTab|FirstTab",
	"Home":             "StartOfTextToggle",
	"End":              "EndOfLine",
	"Ctrl-Home":        "CursorStart",
	"Ctrl-End":         "CursorEnd",
	"PageUp":           "CursorPageUp",
	"PageDown":         "CursorPageDown",
	"Ctrl-PageUp":      "PreviousTab|LastTab",
	"Ctrl-PageDown":    "NextTab|FirstTab",
	"Shift-PageUp":     "SelectPageUp",
	"Shift-PageDown":   "SelectPageDown",
	"Ctrl-g":           "ToggleHelp",
	"Alt-g":            "ToggleKeyMenu",
	"Ctrl-r":           "ToggleRuler",
	"Ctrl-l":           "command-edit:goto ",
	"Delete":           "Delete",
	"Ctrl-b":           "ShellMode",
	"Ctrl-q":           "Quit",
	"Ctrl-e":           "CommandMode",
	"Ctrl-w":           "NextSplit|FirstSplit",
	"Ctrl-u":           "ToggleMacro",
	"Ctrl-j":           "PlayMacro",
	"Insert":           "ToggleOverwriteMode",

	// Emacs-style keybindings
	"Alt-f": "WordRight",
	"Alt-b": "WordLeft",
	"Alt-a": "StartOfText",
	"Alt-e": "EndOfLine",
	// "Alt-p": "CursorUp",
	// "Alt-n": "CursorDown",

	// Integration with file managers
	"F2":  "Save",
	"F3":  "Find",
	"F4":  "Quit",
	"F7":  "Find",
	"F10": "Quit",
	"Esc": "Escape,Deselect,ClearInfo,RemoveAllMultiCursors,UnhighlightSearch",

	// Mouse bindings
	"MouseWheelUp":     "ScrollUp",
	"MouseWheelDown":   "ScrollDown",
	"MouseLeft":        "MousePress",
	"MouseLeftDrag":    "MouseDrag",
	"MouseLeftRelease": "MouseRelease",
	"MouseMiddle":      "PastePrimary",
	"Ctrl-MouseLeft":   "MouseMultiCursor",

	"Alt-n":          "SpawnMultiCursor",
	"Alt-m":          "SpawnMultiCursorSelect",
	"Shift-Alt-Up":   "SpawnMultiCursorUp",
	"Shift-Alt-Down": "SpawnMultiCursorDown",
	"Alt-p":          "RemoveMultiCursor",
	"Alt-c":          "RemoveAllMultiCursors",
	"Alt-x":          "SkipMultiCursor",
}

var infodefaults = map[string]string{
	"Up":               "HistoryUp",
	"Down":             "HistoryDown",
	"Right":            "CursorRight",
	"Left":             "CursorLeft",
	"Shift-Up":         "SelectUp",
	"Shift-Down":       "SelectDown",
	"Shift-Left":       "SelectLeft",
	"Shift-Right":      "SelectRight",
	"Alt-Left":         "StartOfTextToggle",
	"Alt-Right":        "EndOfLine",
	"Alt-Up":           "CursorStart",
	"Alt-Down":         "CursorEnd",
	"Shift-Alt-Right":  "SelectWordRight",
	"Shift-Alt-Left":   "SelectWordLeft",
	"Ctrl-Left":        "WordLeft",
	"Ctrl-Right":       "WordRight",
	"Shift-Ctrl-Left":  "SelectToStartOfTextToggle",
	"Shift-Home":       "SelectToStartOfTextToggle",
	"Shift-Ctrl-Right": "SelectToEndOfLine",
	"Shift-End":        "SelectToEndOfLine",
	"Ctrl-Up":          "CursorStart",
	"Ctrl-Down":        "CursorEnd",
	"Shift-Ctrl-Up":    "SelectToStart",
	"Shift-Ctrl-Down":  "SelectToEnd",
	"Enter":            "ExecuteCommand",
	"Ctrl-H":           "Backspace",
	"Backspace":        "Backspace",
	"OldBackspace":     "Backspace",
	"Alt-Ctrl-h":       "DeleteWordLeft",
	"Alt-Backspace":    "DeleteWordLeft",
	"Tab":              "CommandComplete",
	"Backtab":          "CycleAutocompleteBack",
	"Ctrl-z":           "Undo",
	"Ctrl-y":           "Redo",
	"Ctrl-c":           "Copy",
	"Ctrl-x":           "Cut",
	"Ctrl-k":           "CutLine",
	"Ctrl-v":           "Paste",
	"Home":             "StartOfTextToggle",
	"End":              "EndOfLine",
	"Ctrl-Home":        "CursorStart",
	"Ctrl-End":         "CursorEnd",
	"Delete":           "Delete",
	"Ctrl-q":           "AbortCommand",
	"Ctrl-e":           "EndOfLine",
	"Ctrl-a":           "StartOfLine",
	"Ctrl-w":           "DeleteWordLeft",
	"Insert":           "ToggleOverwriteMode",
	"Ctrl-b":           "WordLeft",
	"Ctrl-f":           "WordRight",
	"Ctrl-d":           "DeleteWordLeft",
	"Ctrl-m":           "ExecuteCommand",
	"Ctrl-n":           "HistoryDown",
	"Ctrl-p":           "HistoryUp",
	"Ctrl-u":           "SelectToStart",

	// Emacs-style keybindings
	"Alt-f": "WordRight",
	"Alt-b": "WordLeft",
	"Alt-a": "StartOfText",
	"Alt-e": "EndOfLine",

	// Integration with file managers
	"F10": "AbortCommand",
	"Esc": "AbortCommand",

	// Mouse bindings
	"MouseWheelUp":     "HistoryUp",
	"MouseWheelDown":   "HistoryDown",
	"MouseLeft":        "MousePress",
	"MouseLeftDrag":    "MouseDrag",
	"MouseLeftRelease": "MouseRelease",
	"MouseMiddle":      "PastePrimary",
}
